functions/session.inc
modules/concom/functions/concom.inc
modules/volunteers/pages/menubar.inc

Previoiusly, IS_VOLUNTEERS (in the _SESSION) was set by looking up in neon.  The concom list is now kept in the DB, neon data is stale and not right anymore.  Moving to the volunteer class to lookup without needing globals.

Tk fix for volunteers menu

---

modules/concom/functions/concom.inc

aliased departments are getting dropped from the google group because the aliases will SOMETIMES show before the department's main email.  I opted for this version instead of calling "not alias" because some of these groups are not the same users in the end.  AFTER the email fix on the google apps domain, this might need to switch to no-alias, but I don't want to decide that until we know the final form of the email domain

Update DumpConComList to include aliases

---

modules/concom/functions/concom.inc

When getDepartmentEmails() changed to returning an array (good thing), this function needed to update to support the extra level of array.  This is a minor fix and only affects the deeplink automation for google groups.

Add support for department emails being arrays

---

tools/deployMe.php

Fixes the autodeploy script and invalidates the old way of updating...  finally.
Note - The two variables (GITHUB_SECRET and GITHUB_BRANCH) Really should be moved to the Configuration database table in a future version)

Deployfix tk - Merge up to dev

---

docker-compose.yml
style.php

With these changes I believe a fresh clean source tree should be able to be started with `./docker_instance up` and update all the php vendor stuff and everything. Ready to directly use.

Composer in Docker

---

modules/concom/functions/concom.inc
modules/concom/pages/menubar.inc
modules/concom/report/pages/body.inc
modules/concom/report/pages/head.inc
modules/concom/report/pages/pre.inc
sitesupport/permissions.js

This ability is added to a department using the `concom.reports` RBAC
entry. By default this is not added to any departments so only ADMIN
users have initial access until it the permission is added to a
department.

Add a ConCom Membership report

---

data/database-schema.php
functions/database.inc
modules/announcements/database-schema.inc
modules/deadlines/database-schema.inc
modules/emailer/database-schema.inc
modules/volunteers/database-schema.inc

This allows us to break down and shorten the master
data/database-schema.php file.
Note: that all pieces of the schema will be loaded even if a module is
disabled. This just allows for far less rebuilding of the database
even if modules are turned on or off.
This patch does not completely remove all the module pieces from the
database-schema.php but it makes a good first pass and establishes a
baseline for modules moving forward.

Allow modules to specify database schema

---

backends/asset/file.inc

`Asset#load` was noisy about missing files. Maybe it should be, but it shouldn't spew 404s for every single request because org-icon isn't in place (unless we're going to supply a default org-icon, in which case, it being missing would be a real error)

Make load less loud

---

sitesupport/common.js

In Javascript, `null` and `undefined` are two different states. Checking for `null` was allowing `undefined` to get tacked on as a parameter to every GET call.
Checking just for existence at all (`if (inParameter)`) does what we want.

Don't add undefined if inParameter is undefined!

---

data/database-schema.php
functions/users.inc
tools/clean_duplicate_accounts.php

This transition is going to be a bit timing sensitive.
You will want to run the clean_duplicate_accounts tool via the web
when there is no neon update running.  Have ?update=1 to do the work
otherwise it will be a dry-run.
Then when the next neon update occures it should properly
not re-duplicate accounts and new neon accounts should not end up as
duplicates.
However if a neon update occures after this patch is applies and
before you run clean_duplicate_accounts, then the neon update will
behave a bit unpredictable around accounts with duplicate email and
may not assige the correct primary account.

Block duplicated email

---

.gitignore
api/src/App/Routes.php
api/src/Controller/BaseController.php
api/src/Controller/Stores/BaseProduct.php
api/src/Controller/Stores/BaseStore.php
api/src/Controller/Stores/DeleteProduct.php
api/src/Controller/Stores/DeleteStore.php
api/src/Controller/Stores/GetProduct.php
api/src/Controller/Stores/GetStore.php
api/src/Controller/Stores/ListProducts.php
api/src/Controller/Stores/ListStores.php
api/src/Controller/Stores/PostProduct.php
api/src/Controller/Stores/PostStore.php
api/src/Controller/Stores/PutProduct.php
api/src/Controller/Stores/PutStore.php
api/src/Handler/ApiError.php
composer.json
composer.lock
data/database-schema.php
modules/store/database-schema.inc

Key features of this PR:
* Introduction of [Atlas Query](http://atlasphp.io/cassini/query/), a relatively light skin over PDO and SQL, to make queries a little less onerous.
* Attempt to be fairly robust with error checking.
* Added to `BaseController` a `filterBodyParameters` method, allowing disallowed parameters to be filtered out, which in turn allows `$body` to be fed directly to certain Atlas statements for insert/update!
* Oh, and actually populate an API for stores and products :-D
This was also unit tested courtesy of Postman's testing capabilities, which are nifty. I'm still learning the ins and outs, but I believe this can eventually be fully automated and added to a CI/CD pipeline. For the moment, however, it can only be accessed within Postman. I have set up a shared team, …

Just the API for Stores and Products.

---

api/src/Controller/BaseController.php
api/src/Controller/Stores/BaseProduct.php
api/src/Controller/Stores/BaseStore.php
api/src/Controller/Stores/GetProduct.php
api/src/Controller/Stores/GetStore.php
api/src/Controller/Stores/PostProduct.php
api/src/Controller/Stores/PostStore.php
api/src/Controller/Stores/PutProduct.php
api/src/Controller/Stores/PutStore.php

Allow 404 handling to be centralized and DRY'd up by having get methods throw a `NotFoundException` instead of having to handle it locally.

Introduce the idea of a NotFoundException handler

---

api/src/Controller/BaseController.php

If SonarCloud still hates it, it will need some rethinking, but this should alleviate it's complaint that `__invoke` was slightly too complex.

Refactor __invoke a bit to appease the complexity meter at SonarCloud

---

functions/database.inc
modules/announcements/database-schema.inc
modules/concom/database-schema.inc
modules/deadlines/database-schema.inc
modules/emailer/database-schema.inc
modules/emailer/functions/emailer.inc
modules/event/database-schema.inc
modules/registration/database-schema.inc
modules/store/database-schema.inc
modules/volunteers/database-schema.inc

Also remove the lingering use of $GLOBALS['DBNAME'] in favour of $_ENV['DBNAME'] as everywhere else.

Deglobalize DB schema init

---

functions/users.inc

If a single account used the same badge name for multiple events
or multiple badges we would get duplicate identical entries.

Correct case where duplicate records where returned from a search

---

Docker.md
FirstSetup.md
api/index.php
api/src/App/App.php
api/src/Modules/concom/ModuleConcom.php
api/src/Tests/Base/CiabTestCase.php
bin/docker_instance.sh
bin/resetdb.sh
bin/run_coverage.sh
bin/run_test.sh
docker-compose.yml
functions/database.inc
functions/functions.inc
index.php
modules/concom/functions/LIST.inc
pages/base/header_start.inc
test/populate_event.php
tools/create_schema.php
tools/test_prereqs.php

Right now, you still have to also run `./bin/resetdb.sh` to truly run with a clean database. This is not ideal, of course, since you may be playing with data in the dev database and not want that wiped out.
So, still to come, a parameterized ./bin/resetdb.sh that just resets either dev or test. But I wanted to get this up for you to start looking at.

Run tests in a separate database with a clean start every time

---

api/src/App/App.php
api/src/Tests/Base/CiabTestCase.php
configure_system.php
docker-compose.yml
index.php

In development where we're now mostly using docker, .env isn't as crucial for setup; in production, it's absolutely required.
`Dotenv\Dotenv::create()` needs to happen before most requires in `index.php` and some other entry-point files, especially before `functions.inc` is required. This PR shifts things around to make that work.
We might want to simply pull the environment variables out of `docker-compose.yml`, to force the two environments to behave more similarly.

Fix environments where we rely on .env 

---

pages/body/create.inc
scss/common.scss

Simple media-query tweak to hide the title when it would make the page header too tall because of wrapping.

Hide title for narrow screens

---

api/src/Modules/registration/Controller/Ticket/ListTickets.php

If something can ever return a list, it should always return a list, even if it's a list of 1 item. That way, parsers don't have to choose.

Always return a list

---

docker/php/Dockerfile

When starting a brand new docker instance for the project, it fails upon installing xdebug. However, since xdebug in the `dockerfile` isn't defining a version, its grabbing the latest xdebug. 
The lastest xdebug is built for php8. This project is running php7, and the [latest xdebug doesn't support php7](https://xdebug.org/docs/compat).
```go
pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.2.7'
```
This can be resolved by defining the xdebug version that works with php7, which is xdebug 2.9. We resolve this by updating dockerfile to expecitly require 2.9.0. Upon this change, docker builds the image and runs.
- [xdebug compatiblity matrix](https://xdebug.org/docs/compat)
- #596

xdebug 2.9.0 for php7

---

.eslintrc.js
api/src/Controller/BaseController.php
babel.config.js
jest.config.js
modules/concom/pages/head.inc
modules/concom/sitesupport/components/staff-division.js
modules/concom/sitesupport/components/staff-list.js
modules/concom/sitesupport/components/staff-section-nav.js
modules/concom/sitesupport/concom_v2.js
modules/concom/sitesupport/division-parser.js
package-lock.json
package.json
test/sitesupport/modules/staff/__tests__/__snapshots__/division-parser.test.js.snap
test/sitesupport/modules/staff/__tests__/department_list.json
test/sitesupport/modules/staff/__tests__/division-parser.test.js

This PR includes:
- Fixes an issue with incorrect values for `child_count` and `email` list in Department API call.
- Adds Jest for JS testing
- Adds initial Vue component code for rendering Division Headers
I am open to moving the JS tests to be closer to where the code actually lives, but for now have included it in `<rootDir>/test/sitesupport`. I wasn't sure how or what is moved over to production servers when a production tag is cut for release.
Not included is actually rendering this - I did not want to commit those changes with this PR, but have been testing with them locally. If you'd like to see the components in action, you can add the following snippet to `<rootDir>/modules/concom/pages/body.inc` between lines 22-24, or wherever you'd like. If done there, it will render at the …

Initial Changes for Splitting ConCom List into front-end/back-end

---

modules/concom/sitesupport/components/department-member.js
modules/concom/sitesupport/components/staff-department.js
modules/concom/sitesupport/components/staff-division.js
modules/concom/sitesupport/components/staff-list.js
modules/concom/sitesupport/components/staff-section-nav.js
modules/concom/sitesupport/components/staff-sidebar.js
modules/concom/sitesupport/concom_v2.js

This PR includes:
- Some cleanup to avoid "prop drilling" (https://vuejs.org/guide/components/provide-inject.html)
- Wires up functionality for clicking on "Add someone to <department or division>", which includes the sidebar and ability to add members only (for now)
- Making use of the new staff positions API
Would like to revisit in the future after we have reached feature parity with existing sidebar implementation. Feature parity for adding was achieved but is a little messy due to providing and injecting extra properties to facilitate allowing the UI to handle the updates without reloading from the server. More details on implementation specifics below.
For example, because the sidebar must be rendered at the same level as "staff list", we cannot easily or simply just emit events …

Continuation of ConCom Split - Add Sidebar

---

api/src/Modules/staff/App/Routes.php
api/src/Modules/staff/Controller/BaseStaff.php
api/src/Modules/staff/Controller/ListDepartmentStaff.php
api/src/Modules/staff/Controller/ListStaff.php
api/src/Tests/Cases/StaffTest.php
ciab.openapi.yaml

* Move /department/staff to /staff as it lists all staff regardless of department.
* Rename `GetDepartment` to `ListDepartmentStaff` as it is much more descriptive and correct
* add `subdepartments` parameter to `ListDepartmentStaff` to list staff in sub-departments of that department (division) is requested

api: refine the staff listing methods

---

api/src/Modules/staff/Controller/BaseStaff.php
api/src/Modules/staff/ModuleStaff.php
modules/concom/functions/RBAC.inc
modules/concom/sitesupport/components/department-member.js
modules/concom/sitesupport/components/staff-department.js
modules/concom/sitesupport/components/staff-list.js

This PR includes:
- Adds RBAC to ModuleStaff in the API.
- Updates to match parity on user permissions for adding members and editing members.
What should be true for each of the positions, based on permissions:
- Admin User
- Can add to any division or department
- Can edit anyone in any division or department
- Division Director
- Can add to the current division or any department within that division
- Can edit Division Support in current division, and anyone in any department within that division
- Division Support
- Can add to any department within that division
- Can edit anyone in any department within that division
- Department Head
- Can add to their department
- Can edit sub-heads and specialists within their department
- Department Sub-Head
- Cannot add to their department
- …

Additional ConCom List Updates

---

modules/concom/scss/concom-list.scss
modules/concom/sitesupport/components/department-header.js
modules/concom/sitesupport/components/department-member.js
modules/concom/sitesupport/components/staff-department.js
modules/concom/sitesupport/components/staff-division.js

This PR includes additional styling changes for special divisions such as Committees and Corporate Staff.
- Adds new specific styles for the special divisions so we can easily change only those later.
- Component updates with templates using conditional rendering for special divisions compared with regular ones
- Component updates for consistency with `methods` definitions
This addresses an issue with mismatched columns for some of these departments and also styles the special divisions in a way that is consistent with the other departments, rather than being half-styled.
I can't add screenshots with before and after images to the PR, but I can shared those if you'd like to see them.

ConCom List Special Division Styles

---

modules/concom/sitesupport/components/staff-division-visual.js
modules/concom/sitesupport/components/staff-list.js
modules/concom/sitesupport/concom_v2.js
modules/concom/sitesupport/division-parser.js
test/sitesupport/modules/staff/__tests__/division-parser.test.js

This PR brings the logic of the ConCom List Donut PHP Code to the front-end.
Included:
- New component for the organizational chart rendering
- New JS function to map data into the expected format for existing Donut JS function
- Leverages same division/department hierarchy data fetch code, and the Donus JS function
Did not completely swap out everything yet, but that should be next.
Next Steps:
- One more sanity check against the recent RBAC changes, then swapping in the new Vue component
- Cleaning up any PHP code that will be unused after that
- Component Library things

ConCom List Organizational Chart

---

modules/concom/sitesupport/components/staff-department.js
modules/concom/sitesupport/components/staff-sidebar.js
modules/concom/sitesupport/division-parser.js
test/sitesupport/modules/staff/__tests__/__snapshots__/division-parser.test.js.snap

This PR includes a couple of bug fixes and one added piece of functionality.
I was able to consistently reproduce the error in `department-member` when _adding_ and _editing_ staff members to divisions. Departments seemed to be unaffected.
The root cause for this is because of the difference in position names for divisions and departments (Director, Support vs Head, Sub-Head, Specialist). In `department-member` when loading data from the server initially, all of positions are returned with `Head`, `Sub-Head` or `Specialist`, however when making updates this was not the case as Division positions were modified to render appropriately in the form, which caused behavior issues afterward.
After my changes I played around with it some more using different combinations of adding, editing, or …

ConCom List Bugfixes

---

modules/concom/sitesupport/division-parser.js
test/sitesupport/modules/staff/__tests__/__snapshots__/division-parser.test.js.snap
test/sitesupport/modules/staff/__tests__/department_list.json
test/sitesupport/modules/staff/__tests__/division-parser.test.js

This PR includes changes to make sure fallback division references are supported in the dorgnut on the ConCom List page.
**Note:** You can safely ignore the file `test/sitesupport/modules/staff/__tests__/department_list.json`, I have simply updated it by calling my API after adding a few fallback divisions and pasting the result from the API output into the file.
- Updates `division-parser` utility functions to capture Fallback Division ID and mapping Dorgnut data appropriately
- Updates the tests for `division-parser`

ConCom Dorgnut Fallback Divisions

---

modules/concom/scss/concom-list.scss

This PR resolves the issue with slow loading on the ConCom List page the first time it is loaded if SCSS is not already cached.
Longer term, it would be nice to get this into a build process (along with JS bundling and some other pieces), but this seems to resolve things for now.
It seems like importing `common` in this file as well as `styles.scss` is likely what caused the issue with compilation speed.

Address Performance issues on ConCom List First Page Load

---

api/src/Core/ModuleDBSchema.php
api/src/Database/DBSchema.php

If we have existing value for these tables we need them to remain and not be changed as there are existing installs that we will be moving to this new DB code which should not be modified.

Do not rewrite core DB values on init

---

modules/concom/sitesupport/division-parser.js
test/sitesupport/modules/staff/__tests__/department_list_prod_sample.json
test/sitesupport/modules/staff/__tests__/division-parser.test.js

This PR addresses an issue that could sometimes lead to some divisions not displaying in the Organizational Donut.
Maintains the current behavior in production where a division is placed as close as possible for its fallback division.

ConCom List Organizational Donut Rendering Issue

---

modules/concom/vue/concom-list.js
modules/concom/vue/staff-division.js
modules/concom/vue/staff-list.js
modules/concom/vue/staff-sidebar.js

This PR includes changes to the UI for the ConCom List to make calls to fetch department staff sequentially rather than firing off all of the requests and waiting for all of them to finish.
Also defines explicit usage of the `updateLoading` function so that the spinner is displayed while loading the full list rather than flashing and then being off screen before requests have finished.

Use Sequential API requests rather than Immediate API requests

---

api/src/App/Dependencies.php
api/src/Controller/Department/ListDepartments.php
api/src/Repository/DepartmentRepository.php
api/src/Service/DepartmentService.php

This PR includes changes necessary to convert from the current inherited Controller model to the Controller -> Service -> Repository pattern.
The changes were made as a first step toward improving overall API performance for this API. I left the `buildResource` function alone for now. Once we are confident with these changes I would recommend removing `buildResource` as a fast-follow. We can also remove the `extends BaseDepartment` at that time, as it will no longer be needed.
When fetching department details I made the judgment call to supply only an ID and Name for the Parent and Fallback Department references. I figured that the data is already available in the response if more than that needs to be used.
I did not add tests, but most of that stems from lack of familiarity with testing …

Convert Department List API to Controller -> Service -> Repo pattern

---

api/src/App/Dependencies.php
api/src/Controller/Department/ListDepartments.php
api/src/Modules/staff/App/Dependencies.php
api/src/Modules/staff/Controller/ListDepartmentStaff.php
api/src/Modules/staff/Repository/StaffRepository.php
api/src/Modules/staff/Service/StaffService.php
api/src/Modules/staff/Settings.php
api/src/Repository/DepartmentRepository.php
api/src/Repository/EventRepository.php
api/src/Repository/MemberRepository.php
api/src/Service/DepartmentService.php
api/src/Service/EventService.php
api/src/Service/MemberService.php

This PR includes performance improvement code that is built upon the Controller -> Service -> Repo pattern that was introduced in this PR: https://github.com/CON-In-A-Box/CIAB-Portal/pull/647 
This code more fully leverages the pattern and demonstrates how we can leverage it to make requests to the DB and cleanly format the response.
There are probably some additional optimizations that could be done where I am currently looping through departments and members by better use of the PHP arrays to leverage keys for the queries. After a few quick tests locally I'm not sure that it will matter too much, but we could consider it for the future.
There are no tests added for the specific service classes here, but I was able to verify the output matched between the original call and new call using …

ConCom List Staff Performance Improvements

---

api/src/Service/MemberService.php

This PR fixes an issue that could occur when an empty array of `$memberIds` is passed into the MemberService, resulting in a SQL error when trying to execute a `WHERE AccountID IN ()` statement.
Instead, if we have no member IDs in the array, an empty array is returned.

Fix an issue in MemberService

---

api/src/Service/MemberService.php
api/src/Tests/Cases/Service/MemberServiceTest.php

This PR adds tests for MemberService. 
In the future, it may be worth considering moving the check for empty memberIds to the repository rather than at the service layer, but ideally we won't have other things calling that repository directly so it may be a non-issue.

Add MemberService Tests

---

modules/concom/vue/StaffStructureApp.js
modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffSidebarDepartmentPermissions.js
modules/concom/vue/components/StaffSidebarEmail.js
modules/concom/vue/components/StaffSidebarPermissions.js
modules/concom/vue/components/StaffStructureDivision.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/currentUser.js
modules/concom/vue/composables/divisionHierarchy.js
modules/concom/vue/views/StaffStructurePage.js

This PR includes a few distinct commits which I can squash as needed.
Initial components for rendering the page with Vue components along with a couple of hooked up "composable" pieces for user permissions to support rendering, and divisions.
Also includes the loosely wired up department sidebar that simply logs when buttons on the sidebar are clicked.
This is still not hooked up on the main page yet, but if you make a couple of changes locally you can see it working.
- In `concom/admin/pages/body.inc`, add the following block starting at the first line:
```
<div id="staff-structure-app">
<staff-structure-page></staff-structure-page>
</div>
```
- In `concom/admin/pages/head.inc` add `<script src="modules/concom/vue/StaffStructureApp.js" type="module"></script>`
No tests yet, but I can …

ConCom Structure Page

---

api/src/Tests/Base/CiabTestCase.php

This PR addresses a memory leak issue we are seeing with tests.
Originally when implementing this against the branch I had been working on for the Department API changes, I was not able to run the tests at all as they would fail after the container started going above 130 MB memory usage. I made no changes to the configuration that would have limited it to this, so I assume it must be a default or something. 
After pulling the latest from `main` I was able to run the tests without these changes, however it was clear that it was leaking memory despite finishing successfully.
Test output before change:
> Time: 39.8 seconds, Memory: 104.00 MB
> 
> OK (102 tests, 2740 assertions)
Test output after change:
> Time: 39.26 seconds, Memory: 32.00 MB
>
> OK (102 tests, 2740 assertions)
No change to …

Fix an issue with memory leaking between tests

---

api/src/App/Routes.php
api/src/Controller/Department/PostDepartment.php
api/src/Modules/staff/Repository/StaffRepository.php
api/src/Modules/staff/Service/StaffService.php
api/src/Repository/DepartmentRepository.php
api/src/Repository/EventRepository.php
api/src/Repository/MemberRepository.php
api/src/Repository/RepositoryInterface.php
api/src/Service/DepartmentService.php
api/src/Service/EventService.php
api/src/Service/MemberService.php
api/src/Service/ServiceInterface.php
api/src/Tests/Cases/DepartmentTest.php
api/src/Tests/Cases/Service/DepartmentServiceTest.php
ciab.openapi.yaml

This PR adds an endpoint to create Departments.
* Changes function return signatures in Repository and Service Interfaces
* I went with `array` but I think ideally the `insert` and `post` function should simply return an ID, so maybe `int` is appropriate here?
* Updates test case in the Department Service
* Re-organize and add tests for API endpoint
* Fixes an issue with memory leaks in the tests
* Not sure how long tests were taking previously, however without this in place I couldn't even successfully run the tests. They were taking a little over a minute for me after the changes.
* Fixes a couple of lint issues that were present in the code
Need to determine the appropriate permission for the new endpoint. Previously there was no permission applied at all. In existing ConCom code, it …

Implement POST Department API Endpoint

---

api/src/App/Dependencies.php
api/src/App/Routes.php
api/src/Controller/Department/DeleteDepartment.php
api/src/Repository/DepartmentRepository.php
api/src/Repository/EmailListAccessRepository.php
api/src/Repository/EmailRepository.php
api/src/Service/DepartmentService.php
api/src/Service/EmailListAccessService.php
api/src/Service/EmailService.php
api/src/Tests/Cases/DepartmentTest.php
api/src/Tests/Cases/Service/DepartmentServiceTest.php
api/src/Tests/Cases/Service/EmailListAccessServiceTest.php
api/src/Tests/Cases/Service/EmailServiceTest.php
ciab.openapi.yaml

This PR adds an endpoint to Delete Departments/Divisions.
Currently there is no permission attached to this, but the original also lacked any sort of permission check on the back-end. I'm not super fond of this and would like to figure out a strategy for this going forward.
It also looks like maybe I need to include some deletes on `EMails` and `EmailListAccess` tables for this call as well, which is not currently implemented.

Add endpoint to delete departments

---

modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffSidebarEmail.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/sidebar.js
modules/concom/vue/composables/sidebarActions.js
modules/concom/vue/views/StaffStructurePage.js

This PR adds the ability to create new divisions and departments on the ConCom Structure Page.
We also gain the ability to switch out the sidebar view, starting with emails, without losing the department data we have filled out, and without using multiple rendered sidebars.
It demonstrates how composables allow us to keep our components clean. We will be able to more easily test our components because we can now mock the composable functions.

Update sidebar with ability to add departments

---

modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffStructureDivision.js
modules/concom/vue/composables/sidebar.js
modules/concom/vue/composables/sidebarActions.js
modules/concom/vue/views/StaffStructurePage.js

This PR adds the necessary changes to get the sidebar working for existing Divisions and Departments.
Some of the names for fields had to change a bit to match up with what data was actually being passed in when an existing division/department was used.

Update Sidebar to Allow Editing of Existing Divisions/Departments

---

api/src/App/Dependencies.php
api/src/App/Routes.php
api/src/Controller/Department/BaseDepartment.php
api/src/Controller/Department/GetDepartmentPermission.php
api/src/Repository/PermissionRepository.php
api/src/Service/DepartmentService.php
api/src/Service/PermissionService.php
api/src/Tests/Cases/DepartmentTest.php
api/src/Tests/Cases/Service/DepartmentServiceTest.php
api/src/Tests/Cases/Service/PermissionServiceTest.php
ciab.openapi.yaml

This MR adds the necessary services and repositories for managing RBAC-based permissions on ConCom Structure page. Also includes the new endpoint, tests, etc.

Add route for listing department permissions

---

modules/concom/vue/components/StaffSidebarDepartmentPermissions.js
modules/concom/vue/components/StaffSidebarPermissions.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/sidebar.js

This PR adds the permissions sidebar screen which displays the dropdown list of permissions to choose from. I kept it in parity with what shows up now, but it would be much more useful to use the descriptions visually in the future.

Add rendering for adding a permission to a department

---

modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffSidebarEmail.js
modules/concom/vue/components/StaffSidebarPermissions.js

This PR brings the Vue implementation for ConCom Structure up to feature parity. It adds confirm boxes that were previously missing for Adding/Removing Departments, Adding Emails, and fixes a typo in the permission form.

Add missing confirm boxes

---

api/src/Controller/Department/PutDepartment.php
api/src/Repository/DepartmentRepository.php
api/src/Tests/Cases/DepartmentTest.php
modules/concom/vue/components/StaffSidebarDepartment.js

This PR addresses a bug in the Vue implementation that prevented a department from being promoted to a division. It also addresses an issue where fallback departments could not be cleared via the UI.

Fix for division to dept and vice versa
