functions/allocations.inc

If non .json files exist in the hotels data direction (such as index.php) do not try to load them as json

Only load json hotel files

---

data/divisions.json
functions/divisional.inc

This makes a number of processing points easier.

Convert divisional Email into an array

---

functions/unit.inc
test/validate_data.php

Validate allocation and divisional data.

First unit test and beginning framework

---

functions/allocations.inc
functions/divisional.inc
functions/functions.inc
functions/neon.inc
pages/body/admin.inc
pages/body/allocations.inc
pages/body/main.inc
pages/body/profile.inc
pages/pre/main.inc
pages/pre/profile.inc
pages/pre/public.inc
pages/pre/volhours.inc

A place where I have found we can generalize some code used over and over

defined a search_definedFields function

---

functions/users.inc
pages/body/volhours.inc
pages/pre/volhours.inc

Aric search for volunteers by email

---

functions/volunteer.inc
pages/body/volunteers.inc

This can be the groundwork for future volunteer hour reporting and manipulation.

Implement a get_volunteer_hours_for_user function

---

pages/body/volhours.inc

Improves issues when searching by e-mail

Mark volunteer Id when known

---

pages/body/volunteers.inc
pages/pre/volunteers.inc

Cleanup on volunteers page

---

functions/users.inc
pages/body/admin.inc
pages/body/volhours.inc
pages/body/volunteers.inc
pages/pre/list.inc
pages/pre/volhours.inc
pages/pre/volunteers.inc

Have more generalized user lookup that returns better errors

Work on user lookup

---

functions/database.inc
functions/divisional.inc
functions/update/from_neon_to_152.inc
functions/volunteer.inc
pages/body/main.inc
pages/body/volhours.inc
pages/body/volunteers.inc
pages/head/volunteers.inc
pages/pre/volhours.inc
test/populate_volunteer.php

Note there is a debug tool I have added
test/populate_volunteer.php
That php script will **WIPE OUT EXISTING** volunteer data (hours, prizes, claims, etc...) and populate the database with a bunch of random data.  That should help visualization of the work. 
Next step is work to allow selection of prizes.

Work to display volunteer hours and prizes

---

functions/volunteer.inc
pages/body/volunteers.inc
pages/pre/volunteers.inc
test/populate_volunteer.php

Aric prizes

---

functions/database.inc
functions/functions.inc

Change to Database for configuration

---

functions/database.inc
functions/update.inc
pages/body/update.inc

Add better framework for updates to the database

---

functions/authentication.inc
functions/volunteer.inc
pages/base/menubar.inc
pages/body/main.inc
pages/body/volunteers.inc
pages/head/volunteers.inc
pages/pre/functions.inc
pages/pre/volunteers.inc
sitesupport/authentication.js
sitesupport/volunteers.js
test/populate_volunteer.php

Much of the work for issue #49 
Cleaned up and proper javascript this time.

Volunteer Administrative Portal

---

pages/body/volunteers.inc

PHP comparison of floats is bad. Fix determing what prizes are ok

---

pages/body/volhours.inc
pages/body/volunteers.inc
pages/head/volhours.inc
pages/head/volunteers.inc
pages/pre/functions.inc
pages/pre/volhours.inc
pages/pre/volunteers.inc
sitesupport/common.js
sitesupport/lookupuser.js
sitesupport/volunteers.js

Have some nice common code for all the places we are looking up a member.

Aric member lookup

---

modules/concom/functions/concom.inc
modules/concom/pages/panes.inc
modules/volunteers/pages/panes.inc
pages/body/main.inc

Move things that are now in loadable modules out of the main page and into loadable panes

Aric main panel

---

modules/volunteers/admin/pages/body.inc
pages/base/menubar.inc

Fix lots of bad php around kiosk modes

---

modules/volunteers/admin/pages/body.inc

Check if 'Aquired' exists before accessing it

---

functions/volunteer.inc
modules/volunteers/admin/pages/body.inc

Rest of the fixes found for issue #68

Fix-ups for php errors generated by volunteers

---

functions/database.inc
modules/volunteers/admin/pages/body.inc
modules/volunteers/admin/pages/pre.inc
modules/volunteers/sitesupport/volunteers.js

Add export of volunteers data direct from database to CSV

---

modules/volunteers/admin/pages/pre.inc
modules/volunteers/pages/menubar.inc

Add and tweak a few page restrictions based on concom status

Aric volpage restrictions

---

README.md
data/database-schema.php
functions/database.inc
functions/functions.inc
functions/update.inc
functions/update/from_152_to_153.inc
index.php
pages/body/update.inc

This adds in all the referential info we've been talking about, needed it to setup for the neon imports

TK - database update to add refers

---

functions/users.inc
pages/pre/functions.inc
sitesupport/lookupuser.js

Add ability to lookup by Badge Name in our user lookup box

---

functions/users.inc

Allow search by prefered name as well.

---

pages/base/leftnav.inc
pages/body/profile.inc

Display the logged in users badge number on left bar and profile page

---

modules/volunteers/admin/pages/body.inc
modules/volunteers/pages/panes.inc
modules/volunteers/sitesupport/volunteers.js

Remove extra zeros from the right had side of volunteer numbers

---

FirstSetup.md
tools/sync_neon_event_to_db.php

Aric issue85

---

modules/volunteers/pages/panes.inc

Move totals on main page

---

data/database-schema.php

Simple tracking table - to be deleted post-Neon interaction

temp table for pull tracking

---

modules/volunteers/admin/pages/body.inc
modules/volunteers/enter/pages/body.inc
modules/volunteers/enter/pages/pre.inc
modules/volunteers/sitesupport/volhours.js
modules/volunteers/sitesupport/volunteers.js
sitesupport/lookupuser.js

Aric improve user lookup fail

---

data/database-schema.php
functions/database.inc
tools/sync_neon_event_to_db.php

Updated field name

---

functions/volunteer.inc
modules/volunteers/admin/pages/body.inc
modules/volunteers/admin/pages/pre.inc
modules/volunteers/sitesupport/volunteers.js

Allow for refund of volunteer prizes

---

.gitignore
data/database-schema.php
functions/database.inc
modules/admin/functions/admin.inc
modules/admin/pages/body.inc

Update to capture (non-Select) queries.  Also display on the admin page.

Tk db activity log

---

modules/volunteers/admin/pages/pre.inc
modules/volunteers/enter/pages/body.inc
modules/volunteers/kiosk/pages/body.inc
modules/volunteers/kiosk/pages/head.inc
modules/volunteers/kiosk/pages/pre.inc
modules/volunteers/pages/menubar.inc
modules/volunteers/sitesupport/volunteers.js
sitesupport/lookupuser.js

Have kiosk mode have a user associated

---

modules/volunteers/admin/pages/head.inc
modules/volunteers/sitesupport/volunteers.js
sitesupport/confirmbox.js

Add confirmation dialog before distribute or return rewards

---

modules/volunteers/enter/pages/body.inc
modules/volunteers/enter/pages/pre.inc
modules/volunteers/sitesupport/volhours.js

Volunteer hours in 15 minute Increments

---

modules/volunteers/enter/pages/body.inc

Also allow the rounding value to be easily changed and customized

Cleanup Volunteer hour rounding

---

functions/session.inc
functions/users.inc
modules/concom/functions/concom.inc

Use ConCom status from database not Neon

---

functions/users.inc

Improve preferred name search to include either first and/or last

---

pages/base/header_start.inc
sitesupport/w3.css

Moving the CSS from W3Schools to the local Repo since it's not CDN Distributed.
Need to do the same with FontAwesome, but FontAwesome did a big upgrade from version 4 to version 5, so I need to hold that until I have time to clean up the differences.

Move W3Schools CSS project local.

---

functions/database.inc
modules/admin/functions/admin.inc
modules/admin/pages/body.inc
modules/admin/pages/pre.inc

Also cleans up CSV output in general

Allow output of DB activity log to CSV

---

modules/volunteers/admin/pages/body.inc

Make Admin mode in Kiosk mode configurable

---

modules/concom/functions/concom.inc
modules/registration/pages/body.inc
modules/registration/pages/head.inc
modules/registration/pages/menubar.inc

Potentially for 2019? Or would we use it for 2018?

Add event registration badge lookup page

---

modules/concom/pages/body.inc
modules/concom/pages/head.inc
modules/concom/pages/pre.inc

Use the proper full member search box we have for concom addition also.

User full member search to add to ConCom

---

modules/volunteers/sitesupport/volhours.js

Correct display of hours and minutes on volunteer timesheet

---

modules/volunteers/enter/pages/body.inc
modules/volunteers/kiosk/pages/body.inc
modules/volunteers/sitesupport/volhours.js
sitesupport/lookupuser.js

For an Issue raised by Sean on Slack.

Add the multiple match selection code to the volhours entry

---

functions/volunteer.inc
modules/volunteers/enter/pages/body.inc
modules/volunteers/enter/upload/pages/pre.inc
modules/volunteers/sitesupport/volhours.js

This now does check for conflicting or duplicate hours. 
For Issue #160

Allow upload of CSV member volunteer hours

---

functions/volunteer.inc
modules/volunteers/pages/panes.inc

Adjust volunteer prize sort

---

data/DBSeed/Configuration.sql
modules/concom/init.inc
modules/volunteers/admin/pages/body.inc
modules/volunteers/pages/panes.inc

ConCom Staff get a set number of volunteer hours

---

modules/volunteers/admin/pages/body.inc
modules/volunteers/pages/panes.inc
modules/volunteers/sitesupport/volunteers.js
test/populate_volunteer.php

Change Prize to Gift in the text on the pages

---

modules/volunteers/admin/pages/body.inc
modules/volunteers/admin/pages/pre.inc
modules/volunteers/pages/menubar.inc

Allow all ConCom access to volunteer department reports

---

data/DBSeed/Configuration.sql
data/database-schema.php
functions/authentication.inc
functions/users.inc
index.php
pages/body/profile.inc
pages/body/public.inc
pages/body/recovery.inc
pages/head/profile.inc
pages/head/recovery.inc
pages/pre/profile.inc
pages/pre/public.inc
pages/pre/recovery.inc
sitesupport/password.js

Migrate user password as they are used from Neon to our local Database.
This will make abandoning Neon much less painful for the user base.
Addresses Issues #83 and #81

Migrate Passwords from Neon

---

functions/volunteer.inc

Also sort that list by department name

List 0 hours departments in volunteer list

---

functions/authentication.inc

Email variable mis-named

---

functions/authentication.inc

what else can I say about Fix #174 ?

over thought the fix

---

modules/volunteers/enter/pages/body.inc

Add more explination around date field in hour import

---

functions/authentication.inc

Send temp passwords to admin

---

functions/database.inc

Fix an error where if we where past the date of the latest even we where not correctly falling back to the last even in the database.

Fix fallback to last event in database

---

functions/database.inc
modules/volunteers/admin/pages/body.inc
modules/volunteers/admin/pages/pre.inc
modules/volunteers/sitesupport/volunteers.js

Expand CVS reporting

---

functions/database.inc
modules/volunteers/admin/pages/body.inc
modules/volunteers/admin/pages/pre.inc

Lookup AccountID Names on derived tables

---

data/DBSeed/Departments.sql
functions/divisional.inc
modules/concom/functions/concom.inc

This is mostly about supporting the separation of CFO from the Systems Division.

format cleanup for CFO Staff - static entry for now

---

modules/documents/pages/menubar.inc

Move Documents out of Admin once setup

---

modules/concom/functions/concom.inc

Fix issue #211

---

data/DBSeed/Departments.sql
functions/divisional.inc
functions/update/to_180924.inc
modules/concom/functions/LIST.inc
modules/concom/functions/POSITION.inc

This fixes issue #209  and generally should be far more robust

Do not make 'Historical Placeholder' ID 0

---

modules/documents/functions/documents.inc
modules/documents/pages/body.inc
modules/documents/pages/pre.inc
modules/documents/sitesupport/documents.js

Allow subfolders in document repository

---

index.php
kiosk/body.inc
kiosk/head.inc
kiosk/kiosk.inc
kiosk/kiosk.js
kiosk/pre.inc
modules/volunteers/admin/pages/body.inc
modules/volunteers/enter/pages/body.inc
modules/volunteers/kiosk/pages/body.inc
modules/volunteers/kiosk/pages/head.inc
modules/volunteers/kiosk/pages/pre.inc
modules/volunteers/pages/menubar.inc
modules/volunteers/sitesupport/volunteers.js
pages/base/menubar.inc

Also move more of the inner working into its own set of methods.
This will make it possible to add kiosk functionality to other
areas of the code. The current vision has kisok functionality
in a registration module as well.

Move the kiosk mode out of the volunteer module

---

configure_system.php
functions/neon.inc
test/neon.php

This specifies a configuration option to use the trial server.
This will mean that existing installs will need to set NEONTRIAL
to continue to function

Neon changed their Demo URLs

---

functions/authentication.inc
functions/users.inc
pages/body/main.inc

This will allow an account with duplicate email addresses to log into
the first instance of the account and warn the user to contact IT
to correct this issue.

Allow login with duplicate accounts

---

pages/head/main.inc
pages/head/profile.inc
pages/head/public.inc
pages/head/recovery.inc

This is to try to help moble users with password problems as
diagnosed by Sean
For Issue #238

Add <meta http-equiv="Cache-control" content="No-Cache"> to pages

---

functions/authentication.inc
pages/body/public.inc
pages/pre/public.inc

Check credentials agenst ALL the accounts to let the user in if
the password matches any of the accounts with the email
Also if everything fails display a warning at the login to help
informe the user that there is a possible issue

Further work to aid in duplicate account handling

---

configure_system.php
functions/neon.inc
kiosk/kiosk.inc
modules/admin/pages/body.inc
modules/concom/admin/pages/body.inc
modules/concom/functions/concom.inc
modules/concom/pages/pre.inc
modules/concom/sitesupport/concom.js
modules/documents/pages/body.inc
modules/event/functions/functions.inc
modules/event/pages/body.inc
modules/registration/pages/body.inc
modules/registration/pages/panes.inc
modules/volunteers/admin/pages/body.inc
modules/volunteers/enter/pages/body.inc
pages/base/disclaimer.inc
pages/base/menubar.inc
pages/body/profile.inc
pages/body/public.inc
pages/body/recovery.inc
pages/body/update.inc
scss/common.scss
sitesupport/authentication.js
sitesupport/confirmbox.js
sitesupport/lookupuser.js

First pass cscss convert

---

functions/users.inc
modules/registration/pages/body.inc
pages/pre/functions.inc
sitesupport/lookupuser.js

This patch will need to be rewritten to move forward off Neon
Test this functionality currently at:
https://ciab.anergyst.org
Under the Member Registration tab

Allow partion user matching for broader lookup

---

modules/event/pages/body.inc
scss/common.scss

Improves mobile/small screen experience

Have all content divs be responsive

---

functions/functions.inc
pages/base/disclaimer.inc
version.ini

More detailed versions string

---

data/DBSeed/EMailLists.sql
data/database-schema.php
modules/concom/functions/POSITION.inc
modules/emailer/functions/emailer.inc
modules/emailer/pages/body.inc
modules/emailer/pages/head.inc
modules/emailer/pages/menubar.inc
modules/emailer/pages/pre.inc
modules/emailer/sitesupport/emailer.js
modules/emailer/sitesupport/emailer2.js.php
scss/common.scss

For Issue #190 
Fully Functional, I believe, new e-mail lists can only be created by an admin. But once given proper access others can edit the lists and send e-mail to the lists.

Emailer Module

---

functions/divisional.inc
modules/concom/functions/concom.inc

Updateing for a change made at last concom to support SRD listing on the ConCom List (all board-reporting positions)
This format will likely not survive the cleanup, but it works for now.

Remove CFO Staff, add Board Staff - SRD Support

---

modules/volunteers/enter/upload/pages/pre.inc

Addresses issues Programming had and have been discussed in e-mail

Allow all of concom to upload hours

---

modules/volunteers/enter/upload/pages/pre.inc

Cache user lookup for speed and reformat date

Aric improve csv import

---

functions/users.inc

Make lookup more robust and easier to use from mobile

Strip whitespace from entered string for user lookup

---

modules/concom/functions/concom.inc

Generally only Admins can make that change

Allow additions to Board Staff

---

backends/RBAC.inc
composer.json
composer.lock
data/database-schema.php
functions/database.inc
modules/admin/pages/menubar.inc
modules/admin/pages/pre.inc
modules/concom/admin/pages/body.inc
modules/concom/admin/pages/head.inc
modules/concom/admin/pages/pre.inc
modules/concom/functions/POSITION.inc
modules/concom/functions/RBAC.inc
modules/concom/functions/concom.inc
modules/concom/init.inc
modules/concom/pages/menubar.inc
modules/concom/sitesupport/concom.js
sitesupport/permissions.js

This will allow the distribution of finer grain access to various parts of the site based on ConCom position.

Start a Role Based Access Control structure

---

modules/concom/sitesupport/concom.js

Correct 0 staff detection for deletion

---

functions/divisional.inc
modules/concom/admin/pages/body.inc
modules/concom/functions/LIST.inc
modules/concom/functions/POSITION.inc
modules/concom/functions/VOLUNTEERS.inc
modules/concom/functions/concom.inc
modules/concom/sitesupport/concom.js

1) Do not display historical departments in the donut
2) Allow deletion of departments with members (Issue #303 and Issue #308)
3) handle deletion of concom membership a bit better (Issue #302 and Issue #304)

Various fixes for ConCom structure around deletion

---

backends/email.inc
backends/email/mail.inc
backends/email/null.inc
backends/email/sendgrid.inc
composer.json
composer.lock

To enable this backend set the following in .env or the environment
EMAIL_BACKEND="sendgrid.inc"
SENDGRID_MAIL_FROM="<email address>"
SENDGRID_API_KEY="<apikey>"

Add sendgrid email backend.

---

functions/divisional.inc

Clean up Departemnt ordering

---

.githooks/pre-commit

activate this using:
git config core.hooksPath .githooks

Add a phpcs githook

---

functions/authentication.inc
functions/functions.inc
index.php

This fixes or at least GREATLY helps the unreliable login issue

Do not destroy "PHPSESSID" when purging cookies

---

modules/concom/pages/menubar.inc
modules/volunteers/pages/menubar.inc

They where non-functional but still appearing

Correct ConCom menus appearing for non-concom members

---

.dockerignore
Docker.md
README.md
configure_system.php
docker-compose.phpmyadmin.yml
docker-compose.yml
docker/apache/Dockerfile
docker/apache/demo.apache.conf
docker/php/Dockerfile
docker_instance.sh

This can of course be expanded and refined as we move forward. But it gives a baseline.

Initial docker starting point

---

.github/workflows/sonarcloud.yml
sonar-project.properties

Sonar Cloud integration

---

.gitignore
scss/scss_cache/.gitignore
style.php

Try to keep generated and web data out of the source portions

Move the scss_cache to resources

---

modules/concom/pages/pre.inc
modules/registration/pages/body.inc

Various Sonarcloud Vulnerabilities resolved

Refactor code to not reflect tainted, user-controlled data.

---

modules/concom/functions/concom.inc
modules/concom/pages/head.inc
modules/concom/sitesupport/concom.js
modules/documents/sitesupport/documents.js
modules/emailer/sitesupport/emailer.js
modules/event/sitesupport/events.js
modules/registration/sitesupport/registration.js
modules/volunteers/sitesupport/volunteers.js
pages/head/profile.inc
pages/head/recovery.inc
sitesupport/confirmbox.js
sitesupport/password.js

Also eleminate window.confirm() usage

Update confirmbox to use Promises

---

functions/divisional.inc
modules/concom/functions/concom.inc

Simple Label fix  (Should likely be configurable at the division level in the future, but not important now)

Changed Board Staff to Board Departments

---

data/database-schema.php
functions/session.inc
modules/concom/functions/ATTENDANCE.inc
modules/concom/functions/concom.inc
modules/concom/pages/panes.inc
modules/concom/pastcredit/pages/pre.inc
phpcs.xml

Placeholder - semifunctional 'but I was there' option for missed meet…ing attendance - Affects #291.  Also, if Aric wants buttons, Aric gets buttons!
Phase two will be deep link email and response handling

Phase 1 - I was there option for meeting attendance

---

data/database-schema.php
functions/divisional.inc
modules/concom/admin/pages/body.inc
modules/concom/admin/pages/pre.inc
modules/concom/functions/concom.inc
modules/concom/pages/body.inc
modules/concom/sitesupport/concom.js
sitesupport/donut.js

For Issue #318  and Issue #319

Division Fallback Representation

---

Docker.md
docker-compose.yml
docker/php/Dockerfile
docker/php/msmtprc
docker/php/php.ini

Fixes #383
1. Persist mysql databases between docker runs.
2. Add mailcatcher and configuration to use it
3. Docco changes to match

Dockerverse Fixes

---

sitesupport/lookupuser.js

Fix an error to the javascript console

---

modules/volunteers/admin/pages/body.inc
modules/volunteers/admin/pages/pre.inc
modules/volunteers/pages/menubar.inc
modules/volunteers/report/pages/body.inc
modules/volunteers/report/pages/head.inc
modules/volunteers/report/pages/pre.inc
modules/volunteers/sitesupport/volunteers.js
pages/base/menubar.inc
scss/common.scss
sitesupport/permissions.js

Groundwork for further report generation.

Split Volunteer reports to separate report menu

---

modules/admin/pages/head.inc
modules/admin/sitesupport/admin.js
modules/concom/sitesupport/concom.js
modules/documents/sitesupport/documents.js
modules/emailer/sitesupport/emailer.js
modules/event/pages/head.inc
modules/event/sitesupport/events.js
modules/registration/sitesupport/registration.js
modules/volunteers/admin/pages/pre.inc
modules/volunteers/sitesupport/volunteers.js
sitesupport/common.js

This is code cleanup to simplify a bunch of the javascript and use a helper function for a lot of the http requests in the modules directory.

backend request

---

functions/database.inc
functions/reports.inc
functions/volunteer.inc
modules/event/functions/functions.inc
modules/event/pages/menubar.inc
modules/event/report/pages/body.inc
modules/event/report/pages/head.inc
modules/event/report/pages/pre.inc
modules/volunteers/report/pages/body.inc
modules/volunteers/report/pages/head.inc
modules/volunteers/report/pages/pre.inc
modules/volunteers/sitesupport/volunteers.js
sitesupport/reportGeneration.js
sitesupport/sidebar.js

Attendance report

---

functions/reports.inc
modules/event/report/pages/pre.inc

Use this to generate attendance reports for all known events

Expand report facility to allow parameters to report functions

---

modules/registration/functions/events.inc
modules/registration/pages/menubar.inc
modules/registration/report/pages/body.inc
modules/registration/report/pages/head.inc
modules/registration/report/pages/pre.inc
sitesupport/permissions.js

Solution for issue #400 , issue #399  and issue #398

Basic Registration Reports

---

backends/RBAC.inc
modules/concom/functions/LIST.inc
modules/concom/functions/RBAC.inc
modules/concom/functions/concom.inc
modules/concom/pages/body.inc
modules/concom/pages/head.inc
modules/concom/pages/menubar.inc
modules/concom/pages/pre.inc
modules/concom/sitesupport/concom.js
scss/common.scss
sitesupport/lookupuser.js
sitesupport/permissions.js

This pass is mostly cleaning up and modernizing.
A little work with the flow of adding members.
Groundwork for issues #307 and #302

concom list work

---

modules/concom/functions/concom.inc
modules/concom/pages/body.inc
modules/concom/pages/pre.inc
modules/concom/sitesupport/concom.js

Enable edit of concom member information

---

modules/concom/functions/concom.inc
modules/concom/pages/body.inc
modules/concom/sitesupport/concom.js

For bug #414 
Also should be helping with the report of being unable to remove concom members

Fix issues with modifying concom

---

functions/users.inc

This is used by Announcements and was causing neon updates to fail for accounts that have made an announcement

Adjust Neon sync to handle foreign keys

---

api/src/Controller/Announcement/PostAnnouncement.php
api/src/Controller/Announcement/PutAnnouncement.php

Properly quote announcement text.

---

modules/concom/functions/concom.inc

Fix resetting callback when deleting a department

---

docker-compose.yml
docker_instance.sh

Docker tweaks

---

data/database-schema.php
functions/database.inc
modules/concom/database-schema.inc

…and allow for multi-column indexes correctly

Improve table creation to handle columns correctly 

---

.vscode/settings.json
api/src/Controller/Member/GetStatus.php

We were not setting `$error` in one of these clauses. I was tempted to refactor this code to be a little less repetitive, but maybe another time.

Fix a missing error string

---

pages/base/menubar.inc
sitesupport/password.js

A number of API fixes and improvements found by first pass of test writing.

Clear local storage on password failure and logout

---

functions/database.inc
functions/functions.inc

Remove a few more blind GLOBAL use.

---

api/doc/Announcement.md
api/doc/Deadline.md
api/doc/Department.md
api/src/App/Routes.php
api/src/Controller/Announcement/PostAnnouncement.php
api/src/Controller/Deadline/PostDeadline.php
api/src/Tests/Cases/AnnouncementTest.php
api/src/Tests/Cases/DeadlineTest.php
modules/announcements/sitesupport/announcements.js
modules/deadlines/sitesupport/deadlines.js

This is MUCH more proper restful syntax

Fix POST method for both announcements and deadlines

---

api/src/Controller/Announcement/BaseAnnouncement.php
api/src/Controller/Announcement/GetAnnouncement.php
api/src/Controller/Announcement/ListDepartmentAnnouncements.php
api/src/Controller/Announcement/ListMemberAnnouncements.php
api/src/Controller/BaseController.php
api/src/Controller/Deadline/GetDeadline.php
api/src/Controller/Department/GetDepartment.php
api/src/Controller/Department/ListDeadlines.php
api/src/Controller/Department/ListDepartments.php
api/src/Controller/Event/BaseEvent.php
api/src/Controller/Member/ListDeadlines.php
api/src/Controller/Permissions/BasePermission.php
api/src/Modules/staff/Controller/BaseStaff.php
api/src/Tests/Cases/AnnouncementTest.php
api/src/Tests/Cases/DeadlineTest.php
api/src/Tests/Cases/DepartmentTest.php
api/src/Tests/Cases/EventTest.php

less code duplication and more directly understandable

Rework how we process API includes

---

api/src/Controller/BaseController.php
api/src/Controller/Stores/BaseStore.php
api/src/Controller/Stores/DeleteStore.php
api/src/Controller/Stores/GetStore.php
api/src/Controller/Stores/ListStores.php
api/src/Controller/Stores/PostStore.php
api/src/Controller/Stores/PutStore.php
api/src/Tests/Base/StoreTestCase.php
api/src/Tests/Cases/Store/DeleteStoreTest.php
api/src/Tests/Cases/Store/GetStoreTest.php
api/src/Tests/Cases/Store/ListStoreTest.php
api/src/Tests/Cases/Store/PostStoreTest.php
api/src/Tests/Cases/Store/PutStoreTest.php
ciab.openapi.yaml
composer.json
composer.lock

This does not yet cover the product sub-API, just Stores crud. Now that I've found a good path, patterns, and rhythm, Product should be easy to revise, but I ran out of oomph.

Revise Stores API, with tests and OAS

---

phpcs.xml

This should make the Atlas code look more like expected

Allow hanging -> chains

---

api/src/Tests/Cases/MemberTest.php
api/src/Tests/Cases/SystemTest.php

Last of the raw SQL left in the API

Remove SQL from tests

---

api/src/Modules/registration/Controller/Ticket/BaseTicket.php
api/src/Modules/registration/Controller/Ticket/PrintQueue.php
api/src/Modules/registration/Controller/Ticket/PrintQueueClaim.php
api/src/Modules/staff/Controller/ListStaff.php
ciab.openapi.yaml

Add a few missing OAS blocks

---

pages/body/create.inc
sitesupport/profile.js

1. The user-profile stuff is nicely modular and will eventually make very nice components!
1. The account creation page was already responsive, but needed to be cut down to the essentials.
1. I did not restyle the page (yet), just cut it down and changed some text. This also means the email-already-taken error being a dialog box is still in place as-is for now.
1. This will now fit on even a fairly small phone screen.
1. Desktop and tablet display will still be horizontally oriented for now.

Account Creation update

---

api/src/Modules/registration/Controller/Ticket/ListTickets.php
modules/registration/boarding/pages/body.inc
modules/registration/boarding/pages/head.inc
modules/registration/checkin/pages/body.inc
modules/registration/checkin/pages/head.inc
modules/registration/lost/pages/body.inc
modules/registration/lost/pages/head.inc
modules/registration/scss/styles.scss
modules/registration/sitesupport/boarding.js
modules/registration/sitesupport/checkin.js
modules/registration/sitesupport/lost.js
modules/registration/sitesupport/manage.js
modules/registration/sitesupport/modules/page.js
modules/registration/sitesupport/modules/ticket.js

* Simplify markup/classes to maximize real estate on small screens. NOTE: this needs a second pass
* Separate Checkin/Boarding/Lost into three pages. NOTE: navigation needs another pass
* Convert a bunch of DOM-manipulation markup to template strings for easier reading/maintenance
* Add some capabilities to ListTickets
As stressed above, a second pass is still needed to really make this pretty and improve navigation, but this is a few inches closer to the wireframes.

Phase 1 Check in and Boarding Revamp

---

api/src/App/App.php
api/src/App/Routes.php
api/src/App/Settings.php
api/src/App/Vendors.php
api/src/Controller/BaseController.php
api/src/Controller/BaseVendorController.php
api/src/Controller/Payment/BasePayment.php
api/src/Controller/Payment/PostPayment.php
api/src/Tests/Base/CiabTestCase.php
api/src/Tests/Cases/PaymentTest.php
api/src/Vendors/Stripe/BasePayment.php
api/src/Vendors/Stripe/PostPayment.php
ciab.openapi.yaml

The first extenstion is the beginning of a Stripe payment processing
system.

Add Vendor extensions for the API

---

sitesupport/profile.js

Also catches case where a field is made blank and properly update that.

Improve profile update logic to only update on field change

---

modules/concom/functions/concom.inc

Fixes the problem with special characters like ' appearing in a name

Escape member data when modifying concom membership

---

modules/concom/functions/LIST.inc

If we have html codes in the database those characters need to be
converted

Continue to sanitize data in the ConCom List

---

modules/registration/pages/head.inc
modules/volunteers/admin/pages/head.inc

Partial revert of 2b1af944a88e283377c2c53eb74dee50c8874cd2

Restore call to console_head()

---

modules/event/functions/functions.inc

Update meeting reports

---

api/src/Controller/Member/BaseMember.php
api/src/Controller/Member/PutMember.php
backends/CRM.inc
backends/CRM/neon.inc

Backend CRM is not going away, so start handling it in the API

Forward member updates from API to CRM

---

modules/volunteers/admin/pages/body.inc
modules/volunteers/admin/sitesupport/giftTable.js
modules/volunteers/admin/sitesupport/vue.js
modules/volunteers/scss/styles.scss
modules/volunteers/sitesupport/hourTable.js
modules/volunteers/sitesupport/volunteers.js

Reduce full page reloads
Clearly display selected volunteers name
Shift a few more things to vue and out of raw javascript.

Volunteer improvements

---

api/src/Controller/BaseController.php
api/src/Modules/staff/App/Routes.php
api/src/Modules/staff/Controller/BaseStaff.php
api/src/Modules/staff/Controller/DeleteStaffMembership.php
api/src/Modules/staff/Controller/GetStaffMembership.php
api/src/Modules/staff/Controller/ListStaffPositions.php
api/src/Tests/Cases/StaffTest.php
ciab.openapi.yaml

Includes:
- Caught `phpcs` related styling errors in BaseController from my last API fix
- Adds API and Documentation for Department Staff Positions
Open to any feedback you'd like to provide on this since I haven't implemented much for PHP changes yet.

API For Staff Positions

---

modules/concom/scss/concom-list.scss
modules/concom/scss/styles.scss
modules/concom/sitesupport/components/department-header.js
modules/concom/sitesupport/components/department-member.js
modules/concom/sitesupport/components/staff-department.js
modules/concom/sitesupport/components/staff-division.js
modules/concom/sitesupport/components/staff-list.js
modules/concom/sitesupport/components/staff-section-nav.js
modules/concom/sitesupport/components/staff-sidebar.js

This PR primarily focuses on styling and rendering improvements for the ConCom List. This PR _does not_ address the difference in formatting for special divisions, that will come in a future PR.
- Specific styling for ConCom List UI
- Made division and department headers consistent
- Made column width consistent for division and department member rows
- Centered most of the content displayed in headers and rows, including within columns
- In a couple of Vue components, I've made things more consistent with method function definitions, and added a few conditional styles
Let me know if you'd like me to provide some screenshots to demonstrate the comparison before and after. I'd be happy to do so.

ConCom List Styling Improvements

---

api/src/App/Install.php
api/src/Controller/Announcement/BaseAnnouncement.php
api/src/Controller/BaseController.php
api/src/Controller/Deadline/BaseDeadline.php
api/src/Controller/Member/FindMembers.php
api/src/Controller/Member/GetConfiguration.php
api/src/Controller/Member/PutConfiguration.php
api/src/Controller/Member/PutMember.php
api/src/Controller/Member/PutPassword.php
api/src/Controller/Permissions/BasePermission.php
api/src/Controller/Permissions/GenericResource.php
api/src/Controller/Permissions/GetMemberPermissions.php
api/src/Controller/TraitScope.php
api/src/Handler/RBAC.php
api/src/Handler/RBACInterface.php
api/src/Modules/staff/Controller/BaseStaff.php
api/src/Modules/staff/Controller/DeleteStaffMembership.php
api/src/Modules/staff/Controller/PostStaffMembership.php
api/src/Modules/staff/Handler/StaffRBAC.php
api/src/Modules/staff/ModuleStaff.php
api/src/Modules/volunteers/ModuleVolunteers.php
api/src/Vendors/Interfaces/RBACVendor.php
api/src/Vendors/Zend/ZendRBACBackend.php

* The RBAC member does not need to be static
* Define interfaces for both the active RBAC and RBAC backend
* Split out the Zend RBAC backend
* Move all the concom/staff RBAC framework into the API module

API: Pull the RBAC code from the concom module into the API

---

modules/concom/sitesupport/division-parser.js
test/sitesupport/modules/staff/__tests__/department_list_circular_fallback.json
test/sitesupport/modules/staff/__tests__/division-parser.test.js

This PR fixes an issue where an infinite loop could occur when the fallback departments are set up to be circular.

ConCom List Circular Fallback in Dorgnut

---

api/src/Service/DepartmentService.php
api/src/Tests/Cases/Service/DepartmentServiceTest.php

This PR adds tests for the `DepartmentService`, including currently unimplemented functions.

Add Department Service Tests

---

api/src/Repository/EventRepository.php
api/src/Service/EventService.php
api/src/Tests/Cases/Service/EventServiceTest.php

This PR adds tests for EventService and also fixes an issue in EventRepository for deleteById.

Add Event Service Tests

---

api/src/Tests/Cases/Modules/staff/Service/StaffServiceTest.php

This PR adds tests for StaffService module.

Add Staff Service Tests

---

api/src/Controller/Announcement/GetAnnouncement.php
api/src/Tests/Base/CiabTestCase.php
api/src/Tests/Base/TestRun.php
api/src/Tests/Cases/AnnouncementTest.php
ciab.openapi.yaml

Make use of in an associative array of values instead of a long list of parameters.

API: Test Case rewrite

---

api/src/App/Routes.php
api/src/Controller/Email/PostEmail.php
api/src/Repository/EmailRepository.php
api/src/Service/EmailService.php
api/src/Tests/Cases/EmailTest.php
api/src/Tests/Cases/Service/EmailServiceTest.php
ciab.openapi.yaml

This PR adds the POST endpoint for the EMail table

Add PostEmail endpoint

---

api/src/App/Routes.php
api/src/Controller/Email/BaseEmail.php
api/src/Controller/Email/GetEmail.php
api/src/Controller/Email/PostEmail.php
api/src/Repository/EmailRepository.php
api/src/Tests/Cases/EmailTest.php
ciab.openapi.yaml

This PR adds the GET endpoint for the EMails table. 
Also (reluctantly) creates the BaseEmail controller to extend from for the purposes of OpenAPI Documentation generation.

Add GetEmail endpoint

---

api/src/App/Routes.php
api/src/Controller/Email/PutEmail.php
api/src/Repository/EmailRepository.php
api/src/Service/EmailService.php
api/src/Tests/Cases/EmailTest.php
api/src/Tests/Cases/Service/EmailServiceTest.php
ciab.openapi.yaml

This PR adds the PUT endpoint for EMails table.

Add Put Email Endpoint

---

modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffSidebarEmail.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/sidebar.js
modules/concom/vue/composables/sidebarActions.js
modules/concom/vue/views/StaffStructurePage.js

PR adds the ability to create new emails for departments in the sidebar on ConCom Structure page.

Add ability to create new department emails in sidebar

---

api/src/App/Routes.php
api/src/Controller/Department/GetDepartmentEmail.php
api/src/Controller/Email/BaseEmail.php
api/src/Repository/EmailRepository.php
api/src/Service/DepartmentService.php
api/src/Service/EmailService.php
api/src/Tests/Cases/DepartmentTest.php
api/src/Tests/Cases/Service/DepartmentServiceTest.php
api/src/Tests/Cases/Service/EmailServiceTest.php
ciab.openapi.yaml

This PR adds an endpoint for departments to get all emails associated with a department.

Add endpoint to get all department emails

---

api/src/App/Routes.php
api/src/Controller/Department/BaseDepartment.php
api/src/Controller/Department/PostDepartmentPermission.php
api/src/Repository/PermissionRepository.php
api/src/Service/PermissionService.php
api/src/Tests/Cases/DepartmentTest.php
api/src/Tests/Cases/Service/PermissionServiceTest.php
ciab.openapi.yaml

This PR includes new endpoint and tests for Department Permissions

New endpoint for creating dept permissions

---

api/src/App/Routes.php
api/src/Controller/Department/DeleteDepartmentPermission.php
api/src/Repository/PermissionRepository.php
api/src/Service/PermissionService.php
api/src/Tests/Cases/DepartmentTest.php
api/src/Tests/Cases/Service/PermissionServiceTest.php
ciab.openapi.yaml

This PR adds an endpoint to delete department permissions and tests.

Add new endpoint to delete department permission

---

modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffSidebarEmail.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/departmentEmail.js
modules/concom/vue/composables/sidebar.js
modules/concom/vue/composables/sidebarActions.js
modules/concom/vue/views/StaffStructurePage.js

This PR adds the ability to update emails in the sidebar in our Vue implementation.

Add ability to update email in sidebar

---

modules/concom/vue/components/StaffSidebarEmail.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/sidebarActions.js
modules/concom/vue/views/StaffStructurePage.js

This PR adds the ability to delete emails using the sidebar

Add ability to delete emails

---

modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffSidebarDepartmentPermissions.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/departmentPermissions.js
modules/concom/vue/composables/departmentStaff.js
modules/concom/vue/composables/sidebar.js
modules/concom/vue/views/StaffStructurePage.js

This PR replaces dummy data in the HTML with real data and renders it. Also implements close button. No other functions implemented yet with this PR.

Renders permissions sidebar with real data

---

modules/concom/vue/components/StaffSidebarPermissions.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/sidebarActions.js
modules/concom/vue/views/StaffStructurePage.js

This PR adds the ability to save permissions for all divisions and departments, and also for individual divisions or departments.

Add ability to save permission

---

modules/concom/vue/components/StaffSidebarDepartmentPermissions.js
modules/concom/vue/components/StaffStructureSidebar.js
modules/concom/vue/composables/sidebarActions.js
modules/concom/vue/views/StaffStructurePage.js

This PR adds the ability to delete a permission from all divisions and departments or specific individual division or department.

Add ability to delete permission from department

---

modules/concom/vue/components/StaffSidebarDepartment.js
modules/concom/vue/components/StaffSidebarEmail.js
modules/concom/vue/components/StaffSidebarPermissions.js

This PR follows https://github.com/CON-In-A-Box/CIAB-Portal/pull/697. Please review/provide feedback on that one before looking to this one.
This fixes an issue that could occur when navigating from the Department Sidebar view to the Email or Permissions view before returning to the Department view again, where the Fallback or Parent Department selection would be lost.

Fix Missing Data for ConCom Structure (Follows #697)
